#pragma once

//#include <entities/destroyer.h>
//#include <entities/droid.h>
//#include <entities/treant.h>
//#include <entities/rocket_thrower.h>
//#include <entities/guardian.h>
//#include <entities/creature.h>
//#include <entities/handthrower.h>
//#include <entities/robot.h>
//#include <entities/spider.h>
//#include <entities/sniper.h>
//#include <entities/monk.h>
//#include <entities/ninja.h>
//#include <entities/absorber.h>
//#include <entities/samurai_rat.h>
//#include <entities/warrior.h>
//#include <entities/wretch.h>
//#include <entities/killer.h>
//#include <entities/giant.h>
//#include <entities/golem.h>
//#include <entities/sorcerer.h>
//#include <entities/combat_robot.h>
//#include <entities/druid.h>
//#include <entities/troll.h>
//#include <entities/poisoner.h>
//#include <entities/soul_hunter.h>
//#include <entities/mechanical_saw.h>
//#include <entities/commander.h>
//#include <entities/gin.h>
//#include <entities/wizzard.h>
//#include <entities/dragon.h>
//#include <entities/reaper.h>
//#include <entities/bomb_instance.h>
//#include <entities/grenadier.h>
//#include <entities/eye.h>
//#include <entities/spectre.h>
//#include <entities/snake.h>
//#include <entities/trailer.h>
//#include <entities/sentinel.h>
