function(add_entity name)
  create_abilities_config_symlink()
  file(GLOB _entity_sources "${CMAKE_CURRENT_SOURCE_DIR}/*.cpp")
  if(_entity_sources)
    add_library(${name} SHARED ${_entity_sources})
    target_include_directories(${name} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
    target_link_libraries(${name} PRIVATE turn_based)
  endif()
endfunction()
